name: MNIST
seed: 1234
track: &track True
model:
  class_name: SimpleCNN
  module_name: src.net.models.simple.cnn
  parameters:
    in_shape: !!python/tuple [28, 28, 1]
    out_channels: 10

dataloader:
  class_name: MNISTLoader
  module_name: src.data.loaders.mnist
  parameters:
    input_size: !!python/tuple [28, 28]
    batch_size: 64
    debug: False

trainer:
  class_name: BaseTrainer
  module_name: src.core.trainer
  parameters:
    num_epochs: 10
    early_stopping_patience: 20
    lr_scheduler: plateau
    lr: 0.00001
    weight_decay: 0.0
    track: *track
    loss:
        module_name: tensorflow.keras.losses
        class_name: SparseCategoricalCrossentropy
        parameters:
          from_logits: False
    metric:
        module_name: tensorflow.keras.metrics
        class_name: SparseCategoricalAccuracy
        parameters:
experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
